export const municipalities = [
    {
        municipality: 'Rivas',
        neighborhoods: [
            '19 de Julio',
            '29 de Mayo',
            'Aníbal Espinales',
            'Apataco',
            'Bautista',
            'Buena Vista',
            'Carlos Aguilar',
            'Ciudadela San Carlos',
            'Colombia',
            'Cristo Rey',
            'Denis Sanches',
            'Eduardo Alvarado',
            'El  Palenque',
            'El Calvario',
            'El Golfo',
            'El Rosario',
            'Fátima',
            'Gaspar García Laviana',
            'José Esteban Corea',
            'José Galiano',
            'La Chocolata',
            'La Conchagua',
            'La Fe',
            'La Puebla',
            'La Virgen',
            'Las Piedras',
            'Los Cerros',
            'Los Pinos',
            'Monte San Juan',
            'Nicarao Calhí',
            'Noel Selva',
            'Obrero',
            'Palo Negro',
            'Pedro Espinoza',
            'Pedro Juaquín Chamorro',
            'Plaza San Pedro',
            'Popoyuapa',
            'Ramón Gonzales',
            'Rigoberto Lopez Perez',
            'San Antonio',
            'San Francisco',
            'San Isidro',
            'San Jerónimo',
            'San Ramon',
            'Santa Ana',
            'Tronco Solo',
            'Veracruz',
            'Villa Offenbach',
            'Villa Violeta',
            'Willfredo Santana',
            'Zaragoza',

        ]
    },
    {
        municipality: 'Tola',
        neighborhoods: [
            'Gaspar García Laviana',
            'Cuascoto',
            'Santiago Campo',
            'El Ojachal',
            'El Tambo',
            'Elvis Zuñiga',
            'Wastomate',
            'Managüita',
            'Evenor Noguera',
            'Nancimí',
            'San Antonio',
            'Las Palomas',
            'Potosí',
            'Rogelio Ramirez',
            'Las Salinas',
            'Rio Grande',
            'Villa Zopolite',
            'Veracruz',
            'Cruz de España',
            'El Murcielago',
            'El Gigante No. 1',
            'El Gigante No. 2',
            'El Coyol',
            'El Palmar',
            'La Junta',
            'Juan Davila',
            'Panamá',
            'Las Pilas',
            'La Flor',
        ]
    },
    {
        municipality: 'Belén',
        neighborhoods: [
            'Belén',
            'Pueblo Nuevo',
            'Cantinplora',
            'Chacalapa',
            'El Descanso',
            'El Jícaro',
            'El Terrero',
            'Escalante',
            'Jocomico',
            'La Cruz',
            'La Uva',
            'Las Mesas',
            'Mancarrón',
            'Mata de Caña',
            'Pica Pica',
            'San José de la Montaña',
            'San Juan Viejo',
        ]
    },
    {
        municipality: 'Potosí',
        neighborhoods: [
            'Apompuá',
            'Potosí',
            'Ochomogo',
            'Pica Pica',
            'Las Banderas',
            'Sabana Grande',
            'Salvador García / Tierra Blanca',
            'Santo Domingo',
            'El Limonal',
            'La Calle de Enmedio',
            'San Isidro',
        ]
    },
    {
        municipality: 'Buenos Aires',
        neighborhoods: [
            'El Cocal',
            'El Limonal',
            'Omar Varela',
            'El Menco',
            'Tolesmayda',
        ]
    },
    {
        municipality: 'San Jorge',
        neighborhoods: [
            'San Antonio',
            'Calle Mercedes',
            'Nicarao Calí',
            'El Progreso',
            'Cruz de España',
            'Santa Carlota',
            'Jorge Camargo',
            'Ramón López',
            'Nuevo Amanecer',
            'Julio Buitrago',
            'El Lago',
            '19 de Julio',
            'El Cangrejal',
            'Arlensiú',
            'Roberto Alvarado',
            'Apataco',
        ]
    },
    {
        municipality: 'San Juan del Sur',
        neighborhoods: [
            'Zona Central',
            'Gaspar Garcia Laviana',
            'El Baston',
            'La Escamequita',
            'Ostional',
            'Boca de Montaña',
            'Las Delicias',
            'El Bastón',
            'El Capulín',
            'El Carrizal',
            'El Ostional',
            'El Pochote',
            'Escamequita',
            'Jenízaro',
            'La Cuesta',
            'La Tortuga',
            'Las Brisa',
            'Las Parcelas',
            'Mira Valle',
            'Monte Cristo',
            'Ojochal',
            'Papaturro',
            'Pueblo Nuevo',
            'San Antonio Norte y Sur',
            'San Jerónimo',
            'Toro Venado',
            'Zaragoza',
            'Casco Urbano',
        ]
    },
    {
        municipality: 'Cárdenas',
        neighborhoods: [
            'Gaspar García Laviana',
            'Las Cañitas',
            'Palos Verdes',
            'Santa Ana',
            'El Progreso',
            'El Triunfo',
            'Rio Mena',
            'Cuajiniquil',
            'Liberación',
            'El Zapotillo',
            'La Flor',
            'Tiruri',
            'Colón',
            'Kalula',
            'Las Mercedes',
            'Sota Caballo',
            'El Acetuno',
            'Los Angeles',
            'El Tablón',
            'Sapoá',
        ]
    },
    {
        municipality: 'Altagracia',
        neighborhoods: [
            'Angul',
            'Balgüe',
            'Calaiza',
            'Corozal',
            'El Madroña',
            'La Cigüeña',
            'La Palma',
            'La Sabana',
            'La Unión',
            'Las Cuchillas',
            'Las Pilas',
            'Los Ramos',
            'Mérida',
            'Pool',
            'Puerto de Gracia',
            'Punta Gorda',
            'San José del Norte',
            'San José del Sur',
            'San Marcos',
            'San Pedro',
            'San Ramón',
            'San Silvestre',
            'Santa Cruz',
            'Santa Teresa',
            'Santo Domingo',
            'Tagüizapa',
            'Sintió Pe',
            'Tichana',
            'Tilgüe',
            'Urbaite',
        ]
    },
    {
        municipality: 'Moyogalpa',
        neighborhoods: [
            'La Paloma',
            'Moyogalpa',
            'Esquipulas',
            'La Concepción',
            'La Flor',
            'Los Ángeles',
            'Sacramento',
            'San José del Sur',
        ]
    },
]
